### ISSUE TITLE
[BUG] pre-commit configuration is very out of date and incompatible

### ISSUE THREAD

**Issue by mgovers** [PowerGridModel/power-grid-model-io#197]
**Describe the bug**

Cannot run `pre-commit run` after new `pre-commit install`

**To Reproduce**

* clean `git clone <repo>`
* `pre-commit install`
* `pre-commit run --all-files`

**Expected behavior**

`pre-commit run --all-files` runs successfully

**Proposed fix**

Bump the pre-commit config to **at least** the following set

```yaml
# SPDX-FileCopyrightText: 2022 Contributors to the Power Grid Model project <dynamic.grid.calculation@alliander.com>
#
# SPDX-License-Identifier: MPL-2.0

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.0.0
    hooks:
      - id: reuse
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        additional_dependencies: [numpy, pandas]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        args: [ "--rcfile=pyproject.toml" ]
        require_serial: true
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [ "--cov-fail-under=100" ]

```

**Additional context**

Only developers are affected
